steps:
  - name: 'gcr.io/cloud-builders/bazel:5.4.0'
    entrypoint: 'bash'
    arga: ['-c',  'echo $$TOKEN']
    secretEnv: ['TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/282516044259/secrets/npmtest/versions/1
    env: 'TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY