steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "Hello bro" >> /root/.npmrc
      tail /root/.npmrc
    secretEnv: ['TOKEN']
    volumes:
    - name: 'home'
      path: /root/
  - name: 'gcr.io/cloud-builders/npm'
    args: ['config', 'get', 'userconfig'] 
    volumes:
    - name: 'home'
      path: /root/
availableSecrets:
  secretManager:
  - versionName: projects/282516044259/secrets/npmtest/versions/1
    env: 'TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY