steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "Hello" >> /root/.npmrc
      tail /root/.npmrc
    secretEnv: ['TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['config', 'list'] 
availableSecrets:
  secretManager:
  - versionName: projects/282516044259/secrets/npmtest/versions/1
    env: 'TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY