steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "Hello bro" >> /builder/home/.npmrc
      tail /builder/home/.npmrc
    secretEnv: ['TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['config', 'get', 'userconfig'] 
  - name: gcr.io/cloud-builders/bazel:5.4.0
    entrypoint: bash
    args: ['tail', '/builder/home/.npmrc']
availableSecrets:
  secretManager:
  - versionName: projects/282516044259/secrets/npmtest/versions/1
    env: 'TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY