#!/bin/bash
set -e


if [ "$(git status --porcelain)" ]; then 
    echo "There are uncommitted changes; aborting." 1>&2
    exit 1
fi

git branch --show-current
git status

if [ "main" != "$(git branch --show-current)" ]; then
    echo "Not on the 'main' branch; aborting." 1>&2
    exit 1
fi
