#!/bin/bash
set -e

echo "Running"

if [ "$(git status --porcelain)" ]; then 
    echo "There are uncommitted changes; aborting." 1>&2
    exit 1
fi


if [ "master" != "$(git branch --show-current)" ]; then
    git branch -m main
fi


if [ "main" != "$(git branch --show-current)" ]; then
    echo "Not on the 'main' branch; aborting." 1>&2
    exit 1
fi

echo "success"
